
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jorge
 */
public class VentanaCaja extends javax.swing.JFrame {
    BaseDatos bd;
    DefaultTableModel m;
    int index=0;
    Producto A[]=new Producto[100];
    RegistroCaja r[]=new RegistroCaja[100];
    double total=0;
    
    /**
     * Creates new form VentanaCaja
     */
    public VentanaCaja() {
        initComponents();
        setLocationRelativeTo(null);

        bd=new BaseDatos();
        try {
            if(bd.conexion.isClosed()){
                System.out.println("Noo!!!. Se cerro");
            }
        } catch (SQLException ex) {
            
            Logger.getLogger(VentanaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        m=(DefaultTableModel) tblProductos.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnVender = new javax.swing.JButton();
        txtCodigoBarra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarLista = new javax.swing.JButton();
        chbManual = new javax.swing.JCheckBox();
        txtCantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtConsultar = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caja");

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodigoBarras", "Nombre", "Descripcion", "Precio", "Cantidad", "ValorTotal"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        btnVender.setBackground(new java.awt.Color(102, 102, 255));
        btnVender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVender.setForeground(new java.awt.Color(255, 255, 255));
        btnVender.setText("Vender");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        txtCodigoBarra.setForeground(new java.awt.Color(153, 153, 153));
        txtCodigoBarra.setText("Ingresa el codigo de barras");

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Venta en caja");

        btnAgregarLista.setBackground(new java.awt.Color(102, 102, 255));
        btnAgregarLista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarLista.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarLista.setText("AGREGAR");
        btnAgregarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarListaActionPerformed(evt);
            }
        });

        chbManual.setForeground(new java.awt.Color(255, 255, 255));
        chbManual.setText("CantidadManual");

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cantidad");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total: 0");

        txtConsultar.setForeground(new java.awt.Color(153, 153, 153));
        txtConsultar.setText("Ingresa el codigo de barras");

        btnConsultar.setBackground(new java.awt.Color(102, 102, 255));
        btnConsultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(351, 351, 351))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAgregarLista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(401, 537, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbManual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarLista)
                    .addComponent(txtCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(lblTotal)
                        .addGap(18, 18, 18)
                        .addComponent(btnVender)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbManual))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultar)
                            .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Regresar al menu empleado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        if (index == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay productos agregados para vender.");
            return; // No hacer nada si no hay productos
        }
        
        if(bd.insertarVenta(new Ventas(0,0,0,total,""))){
            Producto p=new Producto();
            int idVentaU=bd.buscarUltimaVenta();
        
            for (int i = 0; i < m.getRowCount(); i++) {
                p=bd.buscarProducto(r[i].cb, p);
                int c=Integer.parseInt(m.getValueAt(i, 4)+"");
                double precioU=Double.parseDouble(m.getValueAt(i, 3)+"");
                double subTotal=Double.parseDouble(m.getValueAt(i, 5)+"");
                
                bd.insertarDetalleVenta(new DetallesVenta(0, idVentaU, p.id, c, precioU, subTotal));
            }
        }else{
            JOptionPane.showMessageDialog(this, "Error al realizar venta"); return;
        }
        
        
        
    /*      
    double sum = 0;
    for (int i = 0; i < index; i++) {
        bd.insertarDetalleVenta(new DetallesVenta(0, 1, A[i].id, 1, A[i].precioVenta, A[i].precioVenta));
        sum = sum + A[i].precioVenta;
        bd.actualizarVentaTotal(1, sum + "");
    }

    // ==============================
    // Generar ticket de la venta
    // ==============================

    try {
        // Crear nombre de archivo único
        String nombreArchivo = "ticket_" + System.currentTimeMillis() + ".txt";
        
        java.io.FileWriter ticket = new java.io.FileWriter(nombreArchivo);

        ticket.write("====================================\n");
        ticket.write("            P&S\n");
        ticket.write("         TICKET DE COMPRA\n");
        ticket.write("====================================\n\n");

        // Fecha y Hora actuales
        java.time.LocalDateTime fechaHora = java.time.LocalDateTime.now();
        ticket.write("Fecha: " + fechaHora.toLocalDate() + "\n");
        ticket.write("Hora: " + fechaHora.toLocalTime().withNano(0) + "\n\n");

        // Productos desde la tabla
        ticket.write("Productos:\n");
        for (int i = 0; i < tblProductos.getRowCount(); i++) {
            Object nombre = tblProductos.getValueAt(i, 1); // Columna 1 = Nombre
            Object precio = tblProductos.getValueAt(i, 3); // Columna 3 = Precio

            if (nombre != null && precio != null && !nombre.toString().isEmpty()) {
                ticket.write("- " + nombre.toString() + " : $" + precio.toString() + "\n");
            }
        }

        ticket.write("\nTOTAL: $" + String.format("%.2f", sum) + "\n");
        ticket.write("\n¡Gracias por su compra!\n");

        ticket.close();

        // Abrir automáticamente el ticket
        java.awt.Desktop.getDesktop().open(new java.io.File(nombreArchivo));

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error al generar o abrir el ticket.");
    }

    // ==============================
*/
    index = 0;
    limpiarTabla();
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnAgregarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarListaActionPerformed
        Producto p =new Producto();AlmacenC almacen=new AlmacenC();
        String codigo=txtCodigoBarra.getText();
        double sum=0; 
        boolean existe=false;
        p=bd.buscarProducto(codigo, p);
        almacen=bd.buscarAlmacenP(p.id, almacen);
        System.out.println(p.nombre);
        if(p.codigoBarras==null ||almacen.idRegistro==0   ){
            System.out.println("---");//---
            
        }else{
            
            if(chbManual.isSelected()){
                int c=Integer.parseInt(txtCantidad.getText());
                r[index]=new RegistroCaja(p.codigoBarras,p.nombre,p.descripcion,c,almacen.precioV*c,almacen.precioV);
                
                m.addRow(r[index].ObteberArreglo());
            }else{
                for (int i = 0; i < index; i++) {
                    if(m.getValueAt(i, 0).equals(p.codigoBarras)){
                        int c=Integer.parseInt(m.getValueAt(i, 4)+"");
                        double precioU=Double.parseDouble(m.getValueAt(i, 3)+"");
                        m.setValueAt(c+1, i, 4);
                        m.setValueAt((c+1)*precioU, i, 5);
                        
                        existe=true;
                    }  
                }
                if(existe){
                     for (int k = 0; k < index; k++) {
                            sum=sum+Double.parseDouble(m.getValueAt(k, 5)+"");
                        }
                        lblTotal.setText("Total: "+sum);
                        total=sum;
                        existe=false;return;
                }
                r[index]=new RegistroCaja(p.codigoBarras,p.nombre,p.descripcion,1,almacen.precioV,almacen.precioV);
                m.addRow(r[index].ObteberArreglo());
            }
                
        }
        
        
        
        for (int i = 0; i < index; i++) {
            int c=Integer.parseInt(m.getValueAt(i, 4)+"");
            double precioU=Double.parseDouble(m.getValueAt(i, 3)+"");
            sum=sum+(c*precioU);
        }
        lblTotal.setText("Total: "+sum);total=sum;
        
        index++;existe=false;
    }//GEN-LAST:event_btnAgregarListaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
                
       VentanaMenuEmpleado v=new VentanaMenuEmpleado();
        v.bd=bd;
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String cb=txtConsultar.getText();Producto p =new Producto();
        p=bd.buscarProducto(cb, p);
        JOptionPane.showMessageDialog(this, "El producto cuesta: "+p.precioVenta);
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCaja().setVisible(true);
            }
        });
    }
    private void limpiarTabla(){
        for (int i = 0; i < m.getRowCount(); i++) {
            for (int j = 0; j <m.getColumnCount(); j++) {
                m.setValueAt("", i, j);
            }
            
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLista;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnVender;
    private javax.swing.JCheckBox chbManual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoBarra;
    private javax.swing.JTextField txtConsultar;
    // End of variables declaration//GEN-END:variables
}
