
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jorge
 */
public class VentanaCaja extends javax.swing.JFrame {
    BaseDatos bd;
    DefaultTableModel m;
    int index=0;
    Producto A[]=new Producto[100];
    RegistroCaja r[]=new RegistroCaja[100];
    double total=0;
    
    /**
     * Creates new form VentanaCaja
     */
    public VentanaCaja() {
        initComponents();
        setLocationRelativeTo(null);

        bd=new BaseDatos();
        String correoActual = VentanaLogin.correoUsuario;
        System.out.println("Correo obtenido: " + correoActual);
        JLabelCorreoMostrar.setText(VentanaLogin.correoUsuario);
        
        try {
            if(bd.conexion.isClosed()){
                System.out.println("Noo!!!. Se cerro");
            }
        } catch (SQLException ex) {
            
            Logger.getLogger(VentanaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        m=(DefaultTableModel) tblProductos.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVender = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarLista = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        NOMBRE_TITULO = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JLabelCorreoMostrar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        chbManual = new javax.swing.JCheckBox();
        txtCantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        txtConsultar = new javax.swing.JTextField();
        txtCodigoBarra = new javax.swing.JTextField();
        btnReFRess = new javax.swing.JButton();
        txtDinero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caja");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVender.setBackground(new java.awt.Color(204, 0, 0));
        btnVender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVender.setForeground(new java.awt.Color(255, 255, 255));
        btnVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/payment-method.png"))); // NOI18N
        btnVender.setText("VENDER");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });
        jPanel1.add(btnVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, 120, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VENTA EN CAJA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 24, 860, -1));

        btnAgregarLista.setBackground(new java.awt.Color(204, 0, 0));
        btnAgregarLista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarLista.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-producto.png"))); // NOI18N
        btnAgregarLista.setText("AGREGAR");
        btnAgregarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarListaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("Total: 0");
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 170, -1));

        NOMBRE_TITULO.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        NOMBRE_TITULO.setForeground(new java.awt.Color(255, 255, 255));
        NOMBRE_TITULO.setText("P&S");
        jPanel1.add(NOMBRE_TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EMPLEADO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 80, 30));

        JLabelCorreoMostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLabelCorreoMostrar.setForeground(new java.awt.Color(255, 255, 255));
        JLabelCorreoMostrar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(JLabelCorreoMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 220, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodigoBarras", "Nombre", "Descripcion", "Precio", "Cantidad", "ValorTotal"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 790, 330));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 830, 350));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chbManual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chbManual.setForeground(new java.awt.Color(51, 51, 51));
        chbManual.setText("CantidadManual");
        jPanel3.add(chbManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        jPanel3.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 71, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Cantidad");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 63, -1));

        btnConsultar.setBackground(new java.awt.Color(204, 0, 0));
        btnConsultar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search2.png"))); // NOI18N
        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel3.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        txtConsultar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(txtConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 260, 30));

        txtCodigoBarra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(txtCodigoBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 210, 30));

        btnReFRess.setBackground(new java.awt.Color(204, 51, 0));
        btnReFRess.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReFRess.setForeground(new java.awt.Color(255, 255, 255));
        btnReFRess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh-data.png"))); // NOI18N
        btnReFRess.setText("Regrescar Tabla");
        btnReFRess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReFRessActionPerformed(evt);
            }
        });
        jPanel3.add(btnReFRess, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 45, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 830, 80));

        txtDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDineroActionPerformed(evt);
            }
        });
        jPanel1.add(txtDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 570, 120, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dinero.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 570, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, 170, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2849812_menu_multimedia_bars_media_icon.png"))); // NOI18N
        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/353416_home_icon.png"))); // NOI18N
        jMenuItem1.setText("Regresar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2124221_search_document_app_essential_icon.png"))); // NOI18N
        jMenuItem2.setText("Consultar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
    if (index == 0) {
        JOptionPane.showMessageDialog(this, "No hay productos agregados para vender.");
        return;
    }
    
    // Validar dinero suficiente
    double dineroRecibido = 0;
    try {
        dineroRecibido = Double.parseDouble(txtDinero.getText().trim());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingresa una cantidad válida en el campo de pago.");
        return;
    }

    double cambio = dineroRecibido - total;
    if (cambio < 0) {
        JOptionPane.showMessageDialog(this, "El dinero ingresado NO cubre el total. Faltan $" + String.format("%.2f", -cambio));
        return; // ⛔ NO continúa si el dinero es insuficiente
    }

    // ✅ Si pasa la validación, ahora sí se hace la venta
    if (!bd.insertarVenta(new Ventas(0, 0, 0, total, ""))) {
        JOptionPane.showMessageDialog(this, "Error al realizar venta");
        return;
    }
    //Codigo de la caja
    
    CajaGlobal.dineroAcumulado+=total;
    
    Producto p = new Producto();
    int idVentaU = bd.buscarUltimaVenta();

    for (int i = 0; i < m.getRowCount(); i++) {
        p = bd.buscarProducto(r[i].cb, p);
        int c = Integer.parseInt(m.getValueAt(i, 4) + "");
        double precioU = Double.parseDouble(m.getValueAt(i, 3) + "");
        double subTotal = Double.parseDouble(m.getValueAt(i, 5) + "");

        bd.insertarDetalleVenta(new DetallesVenta(0, idVentaU, p.id, c, precioU, subTotal));
        
    }
    bd.actualizarCantidadCaja(total);
    // Preguntar si desea imprimir ticket
    int opcion = JOptionPane.showConfirmDialog(this, "¿Deseas imprimir el ticket?", "Confirmación", JOptionPane.YES_NO_OPTION);

    if (opcion == JOptionPane.YES_OPTION) {
        StringBuilder ticket = new StringBuilder();
        ticket.append("======== P&S ========\n");
        ticket.append("   TICKET DE COMPRA\n");
        ticket.append("======================\n");
        ticket.append("Productos:\n");

        for (int i = 0; i < tblProductos.getRowCount(); i++) {
            Object nombre = tblProductos.getValueAt(i, 1);
            Object cantidad = tblProductos.getValueAt(i, 4);
            Object precio = tblProductos.getValueAt(i, 3);
            Object totalLinea = tblProductos.getValueAt(i, 5);

            if (nombre != null && precio != null && cantidad != null && totalLinea != null) {
                int c = Integer.parseInt(cantidad.toString());
                double precioUnitario = Double.parseDouble(precio.toString());
                double subtotal = c * precioUnitario;
                ticket.append(String.format("- %s | %d x $%.2f = $%.2f\n", nombre, c, precioUnitario, subtotal));
            }
        }

        ticket.append("\nTOTAL: $" + String.format("%.2f", total) + "\n");
        ticket.append("PAGO:  $" + String.format("%.2f", dineroRecibido) + "\n");
        ticket.append("CAMBIO:$" + String.format("%.2f", cambio) + "\n");
        ticket.append("======================\n");
        ticket.append("¡Gracias por su compra!");

        JOptionPane.showMessageDialog(this, ticket.toString(), "Ticket de Compra", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Cambio: $" + String.format("%.2f", cambio));
    }

    // Limpiar después de la venta
    index = 0;
    limpiarTabla();
    actualizarTotal();
    txtDinero.setText("");
    bd.ObtenerDiferencia();


    }//GEN-LAST:event_btnVenderActionPerformed
    private void actualizarTotal() {
        double sum = 0;

        for (int i = 0; i < m.getRowCount(); i++) {
            Object valor = m.getValueAt(i, 5); // Columna 5 = ValorTotal
            if (valor != null && !valor.toString().isEmpty()) {
                sum += Double.parseDouble(valor.toString());
            }
        }

        total = sum;
        lblTotal.setText(String.format("Total: $%.2f", total));
    }

    private void btnAgregarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarListaActionPerformed
      Producto p = new Producto();
    AlmacenC almacen = new AlmacenC();
    String codigo = txtCodigoBarra.getText().trim();
    double sum = 0; 
    boolean existe = false;

    p = bd.buscarProducto(codigo, p);
    almacen = bd.buscarAlmacenP(p.id, almacen);

    if (p.codigoBarras == null || almacen.idRegistro == 0) {
        System.out.println("Producto no encontrado o sin registro en almacén.");
        return;
    }

    if (chbManual.isSelected()) {
        int c = 0;
    try {
        c = Integer.parseInt(txtCantidad.getText().trim());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Ingresa una cantidad válida.");
        return;
    }

    if (c <= 0) {
        JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a cero para agregar el producto.");
        return;
    }

    r[index] = new RegistroCaja(p.codigoBarras, p.nombre, p.descripcion, c, almacen.precioV * c, almacen.precioV);
    m.addRow(r[index].ObteberArreglo());
    index++;
    actualizarTotal();

    } else {
        for (int i = 0; i < index; i++) {
            if (m.getValueAt(i, 0).equals(p.codigoBarras)) {
                int c = Integer.parseInt(m.getValueAt(i, 4) + "");
                double precioU = Double.parseDouble(m.getValueAt(i, 3) + "");
                m.setValueAt(c + 1, i, 4);
                m.setValueAt((c + 1) * precioU, i, 5);
                existe = true;
                break;
            }
        }

        if (existe) {
            actualizarTotal(); // 🔥 También actualiza si solo aumentaste cantidad
            return;
        }

        // Producto nuevo
        r[index] = new RegistroCaja(p.codigoBarras, p.nombre, p.descripcion, 1, almacen.precioV, almacen.precioV);
        m.addRow(r[index].ObteberArreglo());
        index++; // 🔥 Muy importante
        actualizarTotal(); // 🔥 Nuevamente actualiza el total
    }
    }//GEN-LAST:event_btnAgregarListaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
                
       VentanaMenuEmpleado v=new VentanaMenuEmpleado();
        v.bd=bd;
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String cb = txtConsultar.getText().trim(); // código de barras
    Producto p = new Producto();
    p = bd.buscarProducto(cb, p);

    if (p.precioVenta > 0) {
        String mensaje = String.format("Producto: %s\nDescripción: %s\nPrecio: $%.2f MXN",
                                        p.nombre, p.descripcion, p.precioVenta);
        JOptionPane.showMessageDialog(this, mensaje);
    } else {
        JOptionPane.showMessageDialog(this, "Producto no encontrado o sin precio registrado en almacén.");
    }
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
     VentanaConsultaEmpleado v=new VentanaConsultaEmpleado();
        v.bd=bd;
        v.setVisible(true);
        this.dispose();   
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnReFRessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReFRessActionPerformed
        limpiarCampos(); // ✅ Limpia los campos
        actualizarTabla(); // ✅ Actualiza la tabla
        JOptionPane.showMessageDialog(this, "Tabla actualizada.");
    }//GEN-LAST:event_btnReFRessActionPerformed

    private void txtDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDineroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDineroActionPerformed
    private void limpiarCampos() {
        txtCantidad.setText("");
        txtCodigoBarra.setText("");
        txtConsultar.setText("");
        chbManual.setSelected(false);
    }
    private void actualizarTabla() {
        limpiarTabla(); // Borra la tabla actual
        index = 0;       // Reinicia el índice
        total = 0;
        lblTotal.setText("Total: $0.00");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCaja().setVisible(true);
            }
        });
    }
    private void limpiarTabla() {
    m.setRowCount(0); // ✅ Elimina todas las filas de la tabla
}

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelCorreoMostrar;
    private javax.swing.JLabel NOMBRE_TITULO;
    private javax.swing.JButton btnAgregarLista;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnReFRess;
    private javax.swing.JButton btnVender;
    private javax.swing.JCheckBox chbManual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoBarra;
    private javax.swing.JTextField txtConsultar;
    private javax.swing.JTextField txtDinero;
    // End of variables declaration//GEN-END:variables
}
