
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jorge
 */
public class VetnanaGestionUsuarios extends javax.swing.JFrame {
    BaseDatos bd;
    DefaultTableModel m;
    /**
     * Creates new form VetnanaGestionUsuarios
     */
    public VetnanaGestionUsuarios() {
        
        initComponents();
        jMenuItem_Servicios.setText("<html><center>Reporte<br>de ventas</center></html>");
        setLocationRelativeTo(null);

        
        bd=new BaseDatos();
        String correoActual = VentanaLogin.correoUsuario;
        System.out.println("Correo obtenido: " + correoActual);
        JLabelCorreoMostrar.setText(VentanaLogin.correoUsuario);
        
        try {
            if (bd.conexion.isClosed()) {
                System.out.println("Nooo!!!. Se cerró");
            }
        } catch (SQLException ex) {
       //     Logger.getLogger(GestionProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        m=(DefaultTableModel) tblEmpleado.getModel();
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleado = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAgrergar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        JLabelCorreoMostrar = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem_Servicios = new javax.swing.JMenuItem();

        jTextField2.setText("jTextField1");

        jLabel2.setText("Nombre");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Usuarios");
        setPreferredSize(new java.awt.Dimension(860, 500));
        setSize(new java.awt.Dimension(860, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Correo", "Contraseña"
            }
        ));
        jScrollPane1.setViewportView(tblEmpleado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 227, 770, 180));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gestion de Empleados");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 14, 320, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 810, 210));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 20));
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, -1));

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel3.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 240, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Correo:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        jPanel3.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 190, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Constraseña:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        btnAgrergar.setBackground(new java.awt.Color(204, 51, 0));
        btnAgrergar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgrergar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgrergar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-producto.png"))); // NOI18N
        btnAgrergar.setText("Agregar");
        btnAgrergar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrergarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgrergar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 120, -1));

        btnEditar.setBackground(new java.awt.Color(204, 51, 0));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sync.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 100, -1));

        btnBuscar.setBackground(new java.awt.Color(204, 51, 0));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search2.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 110, -1));

        btnEliminar.setBackground(new java.awt.Color(204, 51, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 120, -1));

        btnRefrescar.setBackground(new java.awt.Color(204, 51, 0));
        btnRefrescar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefrescar.setForeground(new java.awt.Color(255, 255, 255));
        btnRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh-data.png"))); // NOI18N
        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });
        jPanel3.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 130, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 810, 130));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GERENTE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 70, 30));

        JLabelCorreoMostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLabelCorreoMostrar.setForeground(new java.awt.Color(255, 255, 255));
        JLabelCorreoMostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(JLabelCorreoMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 180, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 860, 470));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2849812_menu_multimedia_bars_media_icon.png"))); // NOI18N
        jMenu1.setText("Menu");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/353416_home_icon.png"))); // NOI18N
        jMenuItem1.setText("Regresar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenuItem3.setText("Categorias");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inventory.png"))); // NOI18N
        jMenuItem4.setText("Inventario");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/supplier.png"))); // NOI18N
        jMenuItem2.setText("Proveedor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        jMenuItem5.setText("Almacen");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem_Servicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sales.png"))); // NOI18N
        jMenuItem_Servicios.setText("Reporte");
        jMenuItem_Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ServiciosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Servicios);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    String email = txtCorreo.getText().trim();
    String nombre = txtNombre.getText().trim();
    String contrasena = txtContraseña.getText().trim();

    boolean error = false;

    // Restaurar colores
    txtNombre.setBackground(Color.white);
    txtCorreo.setBackground(Color.white);
    txtContraseña.setBackground(Color.white);

    // Validaciones y marcación en rojo
    if (email.isEmpty()) {
        txtCorreo.setBackground(Color.red);
        error = true;
    }
    if (nombre.isEmpty()) {
        txtNombre.setBackground(Color.red);
        error = true;
    }
    if (contrasena.isEmpty()) {
        txtContraseña.setBackground(Color.red);
        error = true;
    }

    if (error) {
        mensaje("ERROR: Todos los campos deben estar llenos.");

        // Temporizador para volver a blanco después de 3 segundos
        new java.util.Timer().schedule(new java.util.TimerTask() {
            @Override
            public void run() {
                txtNombre.setBackground(Color.white);
                txtCorreo.setBackground(Color.white);
                txtContraseña.setBackground(Color.white);
            }
        }, 3000);
        return;
    }

    Empleado e = new Empleado();
    e = bd.buscarEmpleado(email, e); // ← buscas por correo

    if (e == null || e.id == 0) {
        mensaje("ERROR: No se encontró un usuario con ese correo.");
        return;
    }

    // Ahora actualizas campos uno por uno
    boolean nombreActualizado = bd.actualizarEmpleado(e, "Nombre", nombre);
    boolean contrasenaActualizada = bd.actualizarEmpleado(e, "contrasena", contrasena);

    if (nombreActualizado && contrasenaActualizada) {
        mensaje("Usuario actualizado exitosamente.");
        limpiarCampos();
        actualizarTabla(); // Refrescar tabla
    } else {
        mensaje("No se pudo actualizar el usuario.");
    }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String email = txtCorreo.getText().trim();
        Empleado e = new Empleado();

        // Restaurar color
        txtCorreo.setBackground(Color.white);

        // Validación
        if (email.isEmpty()) {
            txtCorreo.setBackground(Color.red);
            mensaje("ERROR: El campo correo está vacío.");

            // Restaurar color tras 3 segundos
            new java.util.Timer().schedule(new java.util.TimerTask() {
                @Override
                public void run() {
                    txtCorreo.setBackground(Color.white);
                }
            }, 3000);
            return;
        }

        // Búsqueda
        e = bd.buscarEmpleado(email, e);

        if (e != null && e.email != null && !e.email.isEmpty()) {
            txtNombre.setText(e.nombre);
            txtCorreo.setText(e.email);
            txtContraseña.setText(e.contr); // Mostrar contraseña
            mensaje("Usuario encontrado.");
        } else {
            mensaje("No se encontró ningún usuario con ese correo.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgrergarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrergarActionPerformed
    String nombre = txtNombre.getText().trim();
    String email = txtCorreo.getText().trim();
    String contraseña = txtContraseña.getText().trim();

    boolean error = false;

    // Restaurar colores antes de validar
    txtNombre.setBackground(Color.white);
    txtCorreo.setBackground(Color.white);
    txtContraseña.setBackground(Color.white);

    if (nombre.isEmpty()) {
        txtNombre.setBackground(Color.red);
        error = true;
    }
    if (email.isEmpty()) {
        txtCorreo.setBackground(Color.red);
        error = true;
    }
    if (contraseña.isEmpty()) {
        txtContraseña.setBackground(Color.red);
        error = true;
    }

    // Si hay campos vacíos, marcamos error y programamos el reset de color
    if (error) {
        mensaje("ERROR: Por favor completa todos los campos.");

        new java.util.Timer().schedule(new java.util.TimerTask() {
            @Override
            public void run() {
                txtNombre.setBackground(Color.white);
                txtCorreo.setBackground(Color.white);
                txtContraseña.setBackground(Color.white);
            }
        }, 3000);
        return;
    }

    // Validar formato de correo
    if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
        txtCorreo.setBackground(Color.red);
        mensaje("Correo inválido. Debe tener un formato válido como ejemplo@dominio.com");

        new java.util.Timer().schedule(new java.util.TimerTask() {
            @Override
            public void run() {
                txtCorreo.setBackground(Color.white);
            }
        }, 3000);
        return;
    }

    // Validar si ya existe en la BD
    if (bd.empleadoExiste(email)) {
        txtCorreo.setBackground(Color.red);
        mensaje("ERROR: Este correo ya está registrado.");

        new java.util.Timer().schedule(new java.util.TimerTask() {
            @Override
            public void run() {
                txtCorreo.setBackground(Color.white);
            }
        }, 3000);
        return;
    }

    // Todo bien, insertamos
    if (bd.insertarEmpleado(nombre, email, contraseña)) {
        mensaje("Empleado registrado exitosamente");
        limpiarCampos();
        actualizarTabla();
    } else {
        mensaje("Error al registrar el empleado.");
    }
    }//GEN-LAST:event_btnAgrergarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String email = txtCorreo.getText().trim();

        // Restaurar color inicial
        txtCorreo.setBackground(Color.white);

        if (email.isEmpty()) {
            txtCorreo.setBackground(Color.red);
            mensaje("ERROR: Campo email vacío");

            // Restaurar color después de 3 segundos
            new java.util.Timer().schedule(new java.util.TimerTask() {
                @Override
                public void run() {
                    txtCorreo.setBackground(Color.white);
                }
            }, 3000);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
            this,
            "¿Seguro que quieres eliminar al empleado?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION
        );

        if (confirmacion != JOptionPane.YES_OPTION) {
            mensaje("Operación cancelada");
            return;
        }

        try {
            if (bd.eliminarEmpleado(email)) {
                mensaje("Empleado eliminado exitosamente");
                limpiarCampos();
                actualizarTabla();
            } else {
                mensaje("Error al eliminar el empleado");
            }
        } catch (Exception e) {
            mensaje("ERROR: Ocurrió un problema al eliminar el empleado");
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
               // TODO add your handling code here:
        VentanaMenu v=new VentanaMenu();
        v.bd=bd;
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        limpiarCampos(); // Limpia los campos de texto
        actualizarTabla(); // Actualiza la tabla con los datos actuales
        mensaje("Tabla actualizada.");
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:

        VentanaGestionCategoria v=new VentanaGestionCategoria();
        v.bd=bd;
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:

        Inventario v=new Inventario();
        v.bd=bd;
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:

        Almacen v=new Almacen();
        v.bd=bd;
        v.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Regresando al menú principal...");

        VentanaMenu v=new VentanaMenu();
        v.bd=bd;
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem_ServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ServiciosActionPerformed
        // TODO add your handling code here:
        VentanaGanancias v=new VentanaGanancias();
        v.bd=bd;
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem_ServiciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VetnanaGestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VetnanaGestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VetnanaGestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VetnanaGestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VetnanaGestionUsuarios().setVisible(true);
            }
        });
    }
    
    public void actualizarTabla(){
        ArrayList<String[]>datos =bd.mostrarEmpleados();
        if(datos.size()==0)return;//---
        int totalRenglones=m.getRowCount();
        for (int i = 0; i <totalRenglones; i++) {
            m.removeRow(0);
        }
        for (String[] data: datos) {
            m.addRow(data);
        }
    }
    public void mensaje(String cad) {
JOptionPane.showMessageDialog(this, cad);
}
    private void limpiarCampos() {
        txtNombre.setText("");
        txtCorreo.setText("");
        txtContraseña.setText("");
        //txtUsuario.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelCorreoMostrar;
    private javax.swing.JButton btnAgrergar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem_Servicios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tblEmpleado;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
